#!/bin/bash
mkdir -p tmp
cd tmp

export DSSSL=/usr/share/xml/docbook/stylesheet/nwalsh/xhtml/chunk.xsl

#/usr/bin/xsltproc --stringparam html.stylesheet docbook.css ../../../docbook-xsl-1.73.2/xhtml/chunk.xsl ../book.xml
/usr/bin/xsltproc --stringparam html.stylesheet docbook.css ${DSSSL} ../book.xml

sed -i "s/{latest}/`date -u`/g" index.html

cd ..

